src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"pseudo"}, message="There is already an account with this pseudo")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $pseudo;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="integer")
     */
    private $codePostal;

    /**
     * @ORM\OneToMany(targetEntity=Commande::class, mappedBy="user", orphanRemoval=true)
     */
    private $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->pseudo;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->codePostal;
    }

    public function setCodePostal(int $codePostal): self
    {
        $this->codePostal = $codePostal;

        return $this;
    }

    /**
     * @return Collection|Commande[]
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setUser($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getUser() === $this) {
                $commande->setUser(null);
            }
        }

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">

		<title>
			{% block title %}Welcome!
			{% endblock %}
		</title>
		{# Run `composer require symfony/webpack-encore-bundle`
								           and uncomment the following Encore helpers to start using Symfony UX #}
		{% block stylesheets %}
			{{ encore_entry_link_tags('app') }}
			<link rel="preconnect" href="https://fonts.gstatic.com">
			<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
		{% endblock %}

		{% block javascripts %}
			{{ encore_entry_script_tags('app') }}
		{% endblock %}
	</head>


	{% block header %}
		{{include("menu.html.twig")}}
	{% endblock %}

	{% block body %}
		<body class="container">
			


				{% for type,messages in app.flashes %}

					{% for msg in messages %}
						<div class="alert alert-{{ type }}">
							{{ msg }}
						</div>
					{% endfor %}

				{% endfor %}

				<h1>
					{% block titreH1 %}
						Bienvenue sur notre ecommerce wf3
					{% endblock %}
				</h1>


			
		</body>
	{% endblock %}
	{% block footer  %}
	
		<footer class="text-center text-lg-start bg-light text-muted container">

			{{include("footer.html.twig")}}

		</footer>
	{% endblock %}
</html>

templates/bestseller.html.twig
<h2 class="text-center p-3">Nos Best-sellers</h2>
	<section class="container produit">
		<h2>Tous les produit </h2>
		<div class="row">
			{% for produit in affichageBestSeller %}

				{# <article class="offset-sm-2 col-sm-8 col-md-5 offset-lg-1 col-lg-5  offset-xl-0 col-xl-4 offset-xxl-0 col-xxl-3"> #}
                <article class="col-4">
					<div class="card  articleProduit  " >
						<img src="/img/{{produit.photo}}" class="card-img-top"  alt="...">
						<div class="card-body">
							<h5 class="card-title">{{produit.nom}}</h5>
							<p class="card-text">{{produit.description}}</p>
							<p class="card-text">{{produit.prix}}</p>

							<a href="{{ path("produit_show", {id: produit.id}) }}" class="btn btn-ghost ">ajouter</a>
							
						</div>
					</div>


				</article>
			{% endfor %}
		</div>
	</section>

templates/footer.html.twig
<section
    class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"
  >
   
    <div class="me-5 d-none d-lg-block">
      <span>Suivez-nous sur les réseaux sociaux:</span>
    </div>
   
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    
  </section>
  

  
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <div class="row mt-3">
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>wf3 
          </h6>
          <p>
            Site développÉ par Franck, Yorann, Morel, Thomas et Marie
          </p>
        </div>
        
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
         
          <h6 class="text-uppercase fw-bold mb-4">
            Produit 
          </h6>
          <p>
            <a href="#!" class="text-reset"> Crème </a>
          </p>
          <p>
            <a href="#!" class="text-reset">Masque</a>
          </p>
          <p>
            <a href="#!" class="text-reset"> Huile démaquillante</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Sérum</a>
          </p>
        </div>
        
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          
          <h6 class="text-uppercase fw-bold mb-4">
            Soins
          </h6>
          <p>
            <a href="#!" class="text-reset">Soin GLOW </a>
          </p>
          <p>
            <a href="#!" class="text-reset">Soin micro-needling</a>
          </p>
         
        </div>
    
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          
          <h6 class="text-uppercase fw-bold mb-4">
            Contactez-nous
          </h6>
          <p><i class="fas fa-home me-3"></i> 1 Avenue des Champs Elysées, 75008 Paris</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            Contact@BeautyWellness.com
          </p>
          <p><i class="fas fa-phone me-3"></i> 01.68.49.23.57 </p>
          
        </div>
       
      </div>
      
    </div>
  </section>
  
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © Copyright 2021 All rights Reserved <br> Il est interdit <b>de le modifier</b> - <b>de le diffuser</b>, y compris <b>sur le web</b> - <b>de se
    l'attribuer</b> - ou <b>de l'utiliser à des fins commerciales et autres</b>. <br>
    Les autorisations au-delà du champ de cette licence peuvent être obtenues auprès de <b>Beauty&Wellness.</b>
    <a class="text-reset fw-bold" href=""></a>
  </div>

templates/menu.html.twig
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
	<a class="navbar-brand" href="{{ path("home") }}">Beauty & Wellness</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">


			{% if is_granted("IS_AUTHENTICATED_FULLY") %}

				{# {% if app.user %} #}


				<li class="nav-item">
					<a class="nav-link" href="{{ path("app_logout") }}">
						<i class="fa fa-sign-out-alt">déconnexion</i>
					</a>
				</li>


				<li class="nav-item ">

					<a class="nav-link" href="{{ path("panier_index") }}"><i class="fas fa-shopping-cart"></i>


					</a>
				</li>


				{% if is_granted("ROLE_ADMIN") %}

					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							Nos Produits
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown">
							<a class="dropdown-item" href="{{ path("produit_index") }}">Liste des produits</a>

							<div class="dropdown-divider"></div>

						</div>
					</li>

					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							Utilisateurs
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown">
							<a class="dropdown-item" href="{{ path("user_index") }}">Liste des utilisateurs</a>

						</div>
					</li>


				{% endif %}
			{% else %}


				<li class="nav-item">
					<a class="nav-link" href="{{ path("app_login") }}">
						<i class="fa fa-user"></i>

						{# {{ app.user.username }} #}
						{#  {{ app.user.pseudo }} #}

					</a>
				</li>

				<li class="nav-item ">
					<a class="nav-link" href="{{ path("app_register") }}">Inscription
					</a>
				</li>


			{% endif %}

			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					Catégories
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					{% for categorie in liste_categories %}


						<a class="dropdown-item" href="{{ path('productByCategorie', {category: categorie.category}) }}">{{categorie.category}}</a>
						{# categorie.category :  category correspond a la valeur du chamlp category  #}
					{% endfor %}
				</div>
			</li>

		</ul>


		<form class="form-inline my-2 my-lg-0" action="{{ path("search") }}">
			<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="mot">
			<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
		</form>
	</div>
</nav>

templates/soin.html.twig
<h2 class="text-center p-3">Nos soins en magasins</h2>

<div class="container soins">


	<div class="row">


		<div class="col-sm-6 col-md-6 p-5">
			<div class="thumbnail">
				<img src="img/masquevert.png" alt="" class="img-thumbnail">
				<div class="caption">
					<h4 class="text-center p-2">
						<p class="text-center">
							Soin masque La Mer - 40€
						</p>
						<div class="col-12 d-flex justify-content-between detail">
							<a href="" class="btn btn-order btn-outline-primary" role="button">
								<span>
									<i class="fas fa-eye"></i>
								</span>
								Voir l'article</a>
							<a href="" class="btn btn-order btn-outline-primary" role="button">
								<span>
									<i class="fas fa-shopping-cart"></i>
								</span>
								Ajouter au panier</a>
						</div>
					</div>
				</div>
			</div>


			<div class="col-sm-6 col-md-6 p-5">
				<div class="thumbnail">
					<img src="img/glow.png" alt=" soin glow" class="img-thumbnail">
					<div class="caption">
						<h4 class="text-center p-2">
							<p class="text-center">
								Soin GLOW - 65€
							</p>

							<div class="col-12 d-flex justify-content-between detail">
								<a href="" class="btn btn-order btn-outline-primary" role="button">
									<span>
										<i class="fas fa-eye"></i>
									</span>
									Voir l'article</a>
								<a href="" class="btn btn-order btn-outline-primary" role="button">
									<span>
										<i class="fas fa-shopping-cart"></i>
									</span>
									Ajouter au panier</a>
							</div>
						</div>
					</div>
				</div>

			</div>
			<div class="row bg-light">
				<div class="col-12">
					<h2 class="text-center p-3">
						Ils parlent de nous :
					</h2>
					<div class="d-flex p-2 container-logo col-lg-4 mb-5 mb-lg-0">
						<img src="img/figaro.png" alt=" soin glow" class="img-thumbnail">
						<img src="img/leseclaireuses.jpg" alt=" soin glow" class="img-thumbnail">
						<img src="img/leparisien.png" alt=" soin glow" class="img-thumbnail">
						<img src="img/public.png" alt=" soin glow" class="img-thumbnail">
					</div>
				</div>
			</div>


			<div class="row bg-light">
				<div class="col-12 offset-1 d-flex justify-content-around p-4">
					<div class="col-3 p-4">
						<img class="w-50" src="" alt="">
					</div>
					<div class="col-3 p-4">
						<img class="w-50" src="" alt="">
					</div>
					<div class="col-3 p-4">
						<img class="w-50" src="" alt="">
					</div>
					<div class="col-3 p-4">
						<img class="w-50" src="" alt="">
					</div>
				</div>
			</div>
		</div>
	</div>
</div>